require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cards", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Card. As you add validations to Card, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {:wallet_id => FactoryBot.create(:company2_wallet_EUR).id}
  }

  let(:invalid_attributes) {
    {:wallet_id => 99}
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # CardsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {:"Company-Id" => 2, :"User-Id" => 3}
  }

  describe "GET /index" do
    it "renders a successful response" do
      card = FactoryBot.create(:card)
      get v1_cards_url, headers: valid_headers, as: :json
      expect(response).to be_successful
      expect(JSON.parse(response.body).size).to eq(1)
    end
  end


  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Card" do
        expect {
          post v1_cards_url,
               params: { card: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Card, :count).by(1)
      end

      it "renders a JSON response with the new card" do
        post v1_cards_url,
             params: { card: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json; charset=utf-8"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Card" do
        expect {
          post v1_cards_url,
               params: { card: invalid_attributes }, as: :json
        }.to change(Card, :count).by(0)
      end

      it "renders a JSON response with errors for the new card" do
        post v1_cards_url,
             params: { card: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json; charset=utf-8")
      end
    end
  end

end
